### ISSUE TITLE
股東姓名找不到資料

### ISSUE THREAD

**Issue by kiang** [ronnywang/twcompany#17]
http://gcis.nat.g0v.tw/id/29073092 看到的 "楊蕙如" ，點下去找不到相關資料

http://gcis.nat.g0v.tw/name/%E6%A5%8A%E8%95%99%E5%A6%82

**Comment by ronnywang** [comment]
修好了

不知道是不是因為剛剛做 apt-get upgrade 時 elasticsearch 就死掉了
把 elasticsearch 重跑了
