### ISSUE TITLE
有些外商公司他的分公司跟本公司的統編一模一樣

### ISSUE THREAD

**Issue by ronnywang** [ronnywang/twcompany#4]
一共 3920 家公司...

Ex: 70824127, 70824344

**Comment by timdream** [comment]
我發現你現在 API 有財政部資料，裡面的`營業人名稱`會出現「...台灣分公司」，可以用這個做字串比對來分嗎？

不過至少就開發票小幫手的 use case 來說，我現在會改抓那邊的名稱 :) 感謝。

**Comment by ronnywang** [comment]
關於這部分，例如 統編的 28970843 ，在以前只能用 "挪威商歐普拉軟體股份有限公司" 來搜尋
如果用 "挪威商歐普拉軟體股份有限公司台灣分公司" 會找不到
但是我前幾天的更新 79bfc43a65af3330897fd37e272c9c400906590f  有讓分公司名稱也能被搜尋到
所以現在用 "挪威商歐普拉軟體股份有限公司"  和 "挪威商歐普拉軟體股份有限公司台灣分公司" 都可以找到了

我剛試 API 確實也是這樣
http://company.g0v.ronny.tw/api/search/?q=%E6%8C%AA%E5%A8%81%E5%95%86%E6%AD%90%E6%99%AE%E6%8B%89%E8%BB%9F%E9%AB%94%E8%82%A1%E4%BB%BD%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8%E5%8F%B0%E7%81%A3%E5%88%86%E5%85%AC%E5%8F%B8
http://company.g0v.ronny.tw/api/search/?q=%E6%8C%AA%E5%A8%81%E5%95%86%E6%AD%90%E6%99%AE%E6%8B%89%E8%BB%9F%E9%AB%94%E8%82%A1%E4%BB%BD%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8

你是用什麼關鍵字搜尋沒找到的呢?˙

**Comment by timdream** [comment]
這個 issue 跟剛剛在 Twitter 上講的事情無關 .... XD

純粹只是想問說既然我那邊可以正確從統編帶出台灣分公司的營業人全名了，那這邊這條 issue 要修好的問題是什麼這樣。

**Comment by ronnywang** [comment]
這個 issue 應該很久以前就可以關了 XD
主要是因為經濟部商業司的公司有三類 1. 公司 2. 分公司 3. 商業登記
而外國公司的總公司在商業司的 1.公司, 2.分公司 裡面都有頁面
所以過去有 bug ，在更新分公司時就把公司資料蓋掉，變成只剩下分公司資料沒有總公司資料

不過這 bug 在今年六月的 72eda15824a1fa0e84eb37eb25fecdcb00d4333c ca274072720f9af3a2172b0a9574ffac921d8999 就修掉了
只是這 issue 一直沒關

然後八月時再補上了”台灣分公司" 也可以被搜尋到的功能
所以分公司這邊功能也更完善了

那我也直接把這邊關掉了 XD

**Comment by timdream** [comment]
所以有外商公司在資料庫裡面會有兩個 entry？有例子嗎？有的話我那邊要再改一下 ....||

**Comment by timdream** [comment]
如果有兩筆的話大概又會再度掉進 timdream/invoice-helper#7 QQ
